### ISSUE TITLE
CustomDataset problem

### ISSUE THREAD

**Issue by sean880304** [quanghuy0497/Mask_R-CNN#3]
Hello, I have a problem. What do "custom_dataset" and "fg" mean in dataset.py. How do I modify those? Thank you.

```
def load_custom(self, dataset_dir, subset):
        """Load a subset of the custom_dataset dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes
        self.add_class("custom_dataset", 1, "fg")
        self.add_class("custom_dataset", 2, "mg")
        self.add_class("custom_dataset", 3, "b")
        self.add_class("custom_dataset", 4, "a")
```

**Comment by sean880304** [comment]
I've set this line in config.py like this:

`NAME = "custom_dataset"  # Override in sub-classes`

when I try to train, I get this error:

File "/home/Mask_R-CNN/dataset.py", line 108, in load_mask
    if p['custom_dataset'] == 'flosser':
KeyError: 'custom_dataset'

How to solve this? Thank you!

**Comment by quanghuy0497** [comment]
> Hello, I have a problem. What do "custom_dataset" and "fg" mean in dataset.py. How do I modify those? Thank you.
> 
> ```
> def load_custom(self, dataset_dir, subset):
>         """Load a subset of the custom_dataset dataset.
>         dataset_dir: Root directory of the dataset.
>         subset: Subset to load: train or val
>         """
>         # Add classes
>         self.add_class("custom_dataset", 1, "fg")
>         self.add_class("custom_dataset", 2, "mg")
>         self.add_class("custom_dataset", 3, "b")
>         self.add_class("custom_dataset", 4, "a")
> ```

Oh these "fg", "mg",... are labels from my personal dataset. You can add/ remove/replace these labels, rename them to fit with your own. Custom dataset are just for a custom data (rather than the publish dataset) where you can modify it freely

**Comment by sean880304** [comment]
> I've set this line in config.py like this:
> 
> `NAME = "custom_dataset" # Override in sub-classes`
> 
> when I try to train, I get this error:
> 
> File "/home/Mask_R-CNN/dataset.py", line 108, in load_mask if p['custom_dataset'] == 'flosser': KeyError: 'custom_dataset'
> 
> How to solve this? Thank you!

@quanghuy0497 Thank you for replying. 
After modifying to my own label, I get this error when trying to train. I couldn't figure out where did I miss?

**Comment by quanghuy0497** [comment]
I think you should look closer to your `dataset.py` file to see if:
1. Is there any error while you customizing the dataset proccessing class?
2. Is the any mismatch to your actual data folder/annotated file?

These 'custom_dataset' and labels i.e. 'fg', 'mg',... in my files can be replaced to fit with your actual data. Also, please check if your data is similar to the format in the README.md file

You can also look for other data processing types in the original repository from Matterport Mark R-CNN

**Comment by sean880304** [comment]
Hi, I found out that my data annotation from VIA is slightly different from your suggested format.

Your is:
```
{ 'filename': '<image_name>.jpg',
           'regions': {
               '0': {
                   'region_attributes': {},
                   'shape_attributes': {
                       'all_points_x': [...],
                       'all_points_y': [...],
                       'name': <class_name>}},
               ... more regions ...
           },
           'size': <image_size>
}
```

and mine is something like this:
```
{"filename":"1.jpg",
	"size":80280,
	"regions":[
		{"shape_attributes":
			{"name":"polygon",
			"all_points_x"[137,303,290,133],
			"all_points_y":[86,83,262,262]},
			"region_attributes":{"type":"bag"}},
		{"shape_attributes":
			{"name":"polygon",
			"all_points_x":[341,511,466,299],
			"all_points_y":[77,79,324,292]},
			"region_attributes":{"type":"flosser"}}],
	"file_attributes":{}
}
```

I'm using this method to annotate:
https://github.com/michhar/maskrcnn-custom

Is this different from your annotation method? Thank you very much!!

**Comment by sean880304** [comment]
OHHH, I've solved this.
Thank you for helping me!!

**Comment by quanghuy0497** [comment]
@sean880304 it's so nice to hear that
