### ISSUE TITLE
overlapped objects problem

### ISSUE THREAD

**Issue by sanhai77** [quanghuy0497/Mask_R-CNN#7]
hi
i have problem in mask branch. in the paper mentioned:
The mask branch has a Km^2- dimensional output for each RoI, which encodes K binary masks of resolution m × m, one for each of the K classes.
but what if we have two overlapped object with same class in one roi?
roi is made of main object + particle of other object(with same class of main object). how mask r-cnn distinct two object for instance segmentation for this roi?
for example in bellow image each rois involve several balloon.
![1_I5_PSpXNmPDp5K9zvUZLpg](https://github.com/quanghuy0497/Mask_R-CNN/assets/141138029/afce35a6-2fab-4c25-a57f-c3888f092cb4)

**Comment by quanghuy0497** [comment]
Hi, @sanhai77 

I am no longer maintaining this repo or being able to provide you with any support, as I have moved to other research projects. I strongly suggest you seek support in the original repo from Matterport's [here](https://github.com/matterport/Mask_RCNN). I believe the community here can support you well.

Sorry for being unable to support you. I hope you will find one soon.

Sincere,

quanghuy0497
